# Generated by Django 3.2 on 2021-05-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('pedigree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('vital_status', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.RenameModel(
            old_name='Pedigree',
            new_name='Member',
        ),
        migrations.DeleteModel(
            name='ExtendedPedigree',
        ),
        migrations.AddField(
            model_name='extendedmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedigree.member'),
        ),
    ]
