# Generated by Django 3.2 on 2021-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0003_auto_20210505_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='generation_level',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ExtendedMember',
        ),
    ]
