# Generated by Django 3.2 on 2021-05-11 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0004_auto_20210505_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created_at']},
        ),
    ]
